# Problem 44

# Pentagon numbers

# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

import math

def is_pentagonal(n):
    return (1 + math.sqrt(1 + 24 * n)) % 6 == 0


def get_pentagonal(n):
    return n * (3 * n - 1) // 2


def find_pentagonal_pair():
    i = 1
    while True:
        i += 1
        p_i = get_pentagonal(i)
        for j in range(i - 1, 0, -1):
            p_j = get_pentagonal(j)
            if is_pentagonal(p_i - p_j) and is_pentagonal(p_i + p_j):
                return p_i - p_j

def main():
    print(find_pentagonal_pair())


main()
