# Problem 45

# Triangle, pentagonal, and hexagonal

# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...

# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...

# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...

# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.


def is_triangle(n):
    return ((8 * n + 1) ** 0.5 - 1) % 2 == 0


def is_pentagonal(n):
    return ((24 * n + 1) ** 0.5 + 1) % 6 == 0


def is_hexagonal(n):
    return ((8 * n + 1) ** 0.5 + 1) % 4 == 0


def find_next_triangle():
    found = False

    while not found:
        n = 286
        while True:
            triangle = n * (n + 1) // 2
            if is_pentagonal(triangle) and is_hexagonal(triangle):
                return triangle
            n += 1


def main():
    print(find_next_triangle())


main()
